[tool.poetry]
name = "repl_python3_JDJGBotSupreme"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2020.4"
emojis = "^0.6.0"
flask = "^1.1.2"
giphy-client = "^1.0.0"
tweepy = "^3.9.0"
dnspython = "^2.0.0"
google-images-search = "^1.3.4"
aiodns = "^2.0.0"
"mystbin.py" = "^1.0.1"
"discord.py" = {extras = ["voice"], version = "^1.6"}
pymongo = "^3.11.2"
bson = "^0.5.10"
sr-api = "^1.1.3"
asuna-api = "^0.2.5"
twemoji-parser = "^0.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
